- platform: mqtt
  state_topic: "/house/attic"
  name: "Attic Sensor"
  unit_of_measurement: "째F"
- platform: mqtt
  state_topic: "/house/duct"
  name: "Duct Sensor"
  unit_of_measurement: "째F"
- platform: mqtt
  state_topic: "/house/return"
  name: "Return Sensor"
  unit_of_measurement: "째F"
- platform: mqtt
  name: "S200 Temperature"
  state_topic: "tele/S200/SENSOR"
  value_template: "{{ value_json['DHT22'].Temperature }}"
  unit_of_measurement: "째F"  
- platform: mqtt
  name: "S200 Humidity"
  state_topic: "tele/S200/SENSOR"
  value_template: "{{ value_json['DHT22'].Humidity }}"
  unit_of_measurement: "%"

- platform: wunderground
  api_key: !secret wunderground_api_key
#  pws_id: KTXNEWBE2
  monitored_conditions:
    - weather
    - observation_time
    - temp_f
    - feelslike_f
    - temp_low_1d_f
    - temp_high_1d_f
    - precip_1d
    - precip_1d_in
    - wind_mph
    - wind_1d_mph
    - alerts
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n

#- platform: speedtest
#  monitored_conditions:
#    - ping
#    - download
#    - upload

- platform: template
  sensors:
    battery_davesi6:
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.davesi6_daf_i6.attributes.battery %}
              {{ states.device_tracker.davesi6_daf_i6.attributes.battery }}
          {% else %}
              {{ states.sensor.battery_davesi6_daf_i6.state }}
          {%- endif %}
      icon_template: >-
          {% set battery_level = states('sensor.battery_davesi6')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
#    battery_air2:
#      unit_of_measurement: '%'
#      value_template: >-
#          {%- if states.device_tracker.air2_air2.attributes.battery %}
#              {{ states.device_tracker.air2_air2.attributes.battery }}
#          {% else %}
#              {{ states.sensor.battery_air2_air2.state }}
#          {%- endif %}
#    battery_jilliphone:
#      unit_of_measurement: '%'
#      value_template: >-
#          {%- if states.device_tracker.jilliphone.attributes.battery %}
#              {{ states.device_tracker.jilliphone.attributes.battery }}
#          {% else %}
#              {{ states.sensor.battery_jilliphone.state }}
#          {%- endif %}

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_utc'
  

- platform: rest
  resource: http://ip.jsontest.com
  name: External IP
  value_template: '{{ value_json.ip }}'

#- platform: octoprint
#  name: OctoPrint
#  monitored_conditions:
#    - Current State
#    - Temperatures
#    - Job Percentage
